### PR TITLE
Attempt to fix Windows builds

### PR DESCRIPTION
**Pull request by gillins**
Currently only `vc9` packages are built. Hoping this is related to the fact that this is related to the `py36` case not being handled....

### CODE REVIEW

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
I think this is good to go @ceholden, seems I had a missing `python  # [win]` build requirement... Hopefully we might be a bit closer to a Windows QGIS with this.

**Comment by ceholden** [comment]
Thanks @gillins! I fixed a similar issue with `libzip` today.

Also rebased [the PR](https://github.com/conda-forge/staged-recipes/pull/5201) that adds a recipe for `qtlocation` and fixed a few things I just noticed (skipping duplicate vc14 build, pinning perl to avoid matrix). Assuming it still builds on the CIs I'll try to get it reviewed again and merged ASAP

**Comment by gillins** [comment]
Thanks @ceholden that seemed to have fixed it.

I just had a look at OSX and found that because the OSX build of `qt` doesn't include `webkit` (uses `webengine` instead) the build failed. [Linux](https://github.com/conda-forge/qt-feedstock/blob/master/recipe/build.sh#L7) and [Windows](https://github.com/conda-forge/qt-feedstock/blob/master/recipe/bld.bat#L5) use `webkit`. I'm not sure what will happen with `qt` 5.9 but we may have to create our own `qwebkit` package for OSX at least...

**Pull request merged**
